### ISSUE TITLE
Was working until later half of 2022 - RX-V683

### ISSUE THREAD

**Issue by Imburr** [mvdwetering/yamaha_ynca#93]
**Describe the bug**
The platform completely failed at some point:

When I click configure on the device I get the errors: "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

Screenshot of device card: https://i.imgur.com/g5UEUza.png

Log:

```
Logger: homeassistant.config_entries
Source: config_entries.py:1089
First occurred: 10:58:32 PM (7 occurrences)
Last logged: 10:59:46 PM

Config entry 'RX-V683' for yamaha_ynca integration not ready yet: Initialization of YNCA receiver RX-V683 failed; Retrying in background
```

And:

```
Logger: aiohttp.server
Source: custom_components/yamaha_ynca/config_flow.py:174
Integration: Yamaha (YNCA) ([documentation](https://github.com/mvdwetering/yamaha_ynca), [issues](https://github.com/mvdwetering/yamaha_ynca/issues))
First occurred: 10:55:42 PM (2 occurrences)
Last logged: 10:59:40 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/yamaha_ynca/config_flow.py", line 174, in async_step_init
    domain_entry_data: DomainEntryData = self.hass.data[DOMAIN].get(
KeyError: 'yamaha_ynca'
```

**To Reproduce**

Install integration through HACS. Add device. Put in device IP address.

**Expected behavior**

It used to work great, and I have a few automations built off of it.

**Diagnostics**
If possible add diagnostics data from HA. The "Download diagnostics" option can be found in the vertical 3 dots menu (⋮) of the integration.

Please add the file itself (drag-and-drop in this box). Do not, copy-paste the contents here as it will make the issue unreadable

**Logging**
If there are errors in the Home Assistant logs please add them here.

**Home Assistant version information:**
 - HASS.io 2022.11.3
 - HACS Plugin v5.2.0

**Comment by mvdwetering** [comment]
The error in the logs is caused because the Options screen is opened with the Configure button on the Integration card when the integration is not setup (which needs to be handled better). 

Unfortunately that is not the reason why the integration was not able to not setup in the first place.

Could you enable debug logging for this integration?
In the `configuration.yaml` add or extend the following `logging` section. so it includes the  debug logging for this component. Then restart Home Assistant and attach the Home Assistant logfile so I can examine it.

```
logger:
  default: info
  logs:
    ynca: debug
    custom_components.yamaha_ynca: debug
```

After grabbing the logging the `configuraion.yaml` can be restored.

(if in the mean time you upgraded to HA 2022.12 you can enable debug logging from the integration card and reload the integration, then disable debug logging and the log will be downloaded)

![image](https://user-images.githubusercontent.com/732514/208248551-34725ea2-ee32-4984-8ab8-fc279346d738.png)

**Comment by Imburr** [comment]
Ok, I enabled logging, and I updated the HACS addon and I also updated HA, and its working now. So whatever was the problem, seems fixed. Do you still want me to send logs? If so, where do I grab them from once debug is enabled?

**Comment by mvdwetering** [comment]
Whatever it was it is gone, I don't see a need for logs anymore. 
Glad it is working for you now.
